Update implementation of Tokenizable for Vec<u8>
tomusdrw/rust-web3 pull request #377
Opened 2020-09-24 05:03 UTC by ducthotran2010

The contract call could return `uint8[]` instead of `bytes`, but `Vec<u8>` implementation just supports `bytes`.

2020-09-24 09:40 UTC, tomusdrw requested changes

2020-09-24 09:40 UTC, tomusdrw commented on src/contract/tokens.rs
> +            Token::Array(tokens) | Token::FixedArray(tokens) => {
The problem with this is that you will decode `Vec<u8>` from `Token::Array`, but encoding (`into_tokens`) will always return `Token::Bytes` which is quite misleading.

The split is done on purpose currently (also a bit due to Rust limitations). I think the best way forward would be to introduce a type that looks like this:
```rust
pub struct BytesArray(pub Vec<u8>);
impl Tokenizable for BytesArray {
    fn from_token(token: Token) -> Result<Self, Error> {
        match token {
            Token::FixedArray(tokens) | Token::Array(tokens) => {
                Ok(Self(tokens.into_iter().map(Tokenizable::from_token).collect()?))
            }
            other => Err(Error::InvalidOutputType(format!("Expected `Array`, got {:?}", other))),
        }
    }

    fn into_token(self) -> Token {
        Token::Array(self.into_iter().map(Tokenizable::into_token).collect())
    }
}
```

Unless `Token::Bytes` and `Token::Array` have the same ethabi encoding and there is no confusion here (I really don't remember).

Also please add tests.

2020-09-24 13:30 UTC, tomusdrw reviewed
Awesome, thanks! tiny doc improvement

2020-09-24 13:30 UTC, tomusdrw commented on src/types/bytes_array.rs
> +/// Array of bytes wrapper
```suggestion
/// A wrapper type for array of bytes.
/// 
/// Implements `Tokenizable` so can be used to retrieve data from `Solidity` contracts returning `byte8[]`.
```

2020-09-24 13:31 UTC, tomusdrw approved these changes

2020-09-24 18:41 UTC, merged

2020-09-24 18:41 UTC, tomusdrw commented
Thank you!

2020-09-25 14:25 UTC, ducthotran2010 commented on src/types/bytes_array.rs
> +/// Array of bytes wrapper
Nice