Update README and add badges
tomusdrw/rust-web3 pull request #413
Opened 2020-11-25 09:54 UTC by elpiel

Closes #412 

I am looking for feedback and discussion on the changes, as I think reflecting the actual crate name is better for users overall.
Also not sure about the documentation, is there a reason to use the github pages?

2020-11-25 11:09 UTC, tomusdrw requested changes
LGTM, just two tiny clarifications about the docs needed.

2020-11-25 11:09 UTC, tomusdrw commented on README.md
> +[documentation-badge]: https://img.shields.io/badge/Documentation-tomusdrw.github.io%2Frust--web3-blue
```suggestion
[documentation-badge]: https://img.shields.io/badge/Documentation-master%20branch-blue
```

2020-11-25 11:09 UTC, tomusdrw commented on README.md
> +Documentation: [tomusdrw.github.io/rust-web3][documentation-url] or [docs.rs/web3](docs-rs-url)
github pages documentation is for the `master` branch, and I think due to random release cycle it's still useful.

```suggestion
Documentation: [master branch][documentation-url] or [crates.io](docs-rs-url)
```

2020-11-25 11:59 UTC, elpiel commented
Great!

2020-11-25 12:16 UTC, tomusdrw reviewed
sorry, noticed that the docs link doesn't work

2020-11-25 12:16 UTC, tomusdrw commented on README.md
> +Documentation: [master branch][documentation-url] or [crates.io](docs-rs-url)
```suggestion
Documentation: [master branch][documentation-url] or [crates.io][docs-rs-url]
```

2020-11-26 10:27 UTC, elpiel commented
lgtm

2020-11-26 10:45 UTC, tomusdrw approved these changes

2020-11-26 10:46 UTC, merged